image: docker:latest

services:
  - docker:dind

variables:
  DOCKERFILE_FLAVOUR: debian
  PHP_BASE_IMAGE_VERSION: fpm
  PHP_IMAGE_NAME: yiiframework/php
  TEST_YII_VERSION: 2.0.15.1

before_script:
  - apk add --no-cache python py2-pip git
  - pip install --no-cache-dir docker-compose==1.16.0
  - git clone https://github.com/yiisoft/yii-dev-tool _host-volumes/yii-dev-tool
  - pushd _host-volumes/yii-dev-tool && git checkout ${TEST_YII_VERSION} && popd
  - docker info

build:
  environment:
    name: ${DOCKERFILE_FLAVOUR}/php-${PHP_BASE_IMAGE_VERSION}
  script:
    - docker-compose build
    - docker-compose run --rm php php -v
    - docker-compose run --rm php php /tests/requirements.php
    - docker-compose run --rm -w /yii-dev-tool php composer install
      # TODO: install and test "core" packages
    #- docker-compose run --rm -w /yii-dev-tool php php -d error_reporting="E_ALL ^ E_DEPRECATED" vendor/bin/phpunit tests/framework/ --exclude db
    - docker-compose run --rm php npm -v
