language: bash
services: docker

env:
  global:
    - GITHUB_API_TOKEN: ''
    - TEST_YII_VERSION: 'master'
    - PHP_IMAGE_NAME: 'yiisoftware/yii-php'
  jobs:
    - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.4-fpm
    - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.4-apache

before_install:
  - if [ -n "$TRAVIS_TAG" ]; then export PHP_IMAGE_VERSION_SUFFIX=-${TRAVIS_TAG}; fi

install:
  - git clone https://github.com/yiisoft/yii-dev-tool _host-volumes/yii-dev-tool
  - pushd _host-volumes/yii-dev-tool && git checkout ${TEST_YII_VERSION} && popd

before_script:
  - pwd
  - docker version
  - docker info
  - docker-compose version

script:
  - echo "travis_fold:start:BUILD folding starts"
  - docker-compose build
  - echo "travis_fold:end:BUILD folding ends"
  - docker-compose run --rm php php -v
  - docker-compose run --rm php npm -v
  - docker-compose run --rm php php /tests/requirements.php
  - docker-compose run --rm -w /yii-dev-tool php composer install
  # TODO: install and test "core" packages
  #- docker-compose run --rm -w /yii-dev-tool php ./yii-dev install validator

after_script:
  - docker images

after_success:
  - if [[ $TRAVIS_BRANCH = "master" || -n "$TRAVIS_TAG" ]]; then
      echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin  &&
      docker-compose push;
    fi

# vim:set et ts=2 sw=2:

notifications:
  slack:
    -
      rooms:
        -
          secure: BnVc1R1O+iSOfQu+WCpj98NV1GXmg5tO9a2rn35/GAAWrtoWRZ6EQobtY8b+hV9ZxV8aErnREeoDlKjabRpPaHa5vl5f7V06RsaKuBg2rfCNuyOv1S6wWUyVH+KFu8XW73sICvqDYtgsbaVs8mUC2xhNEsqo+fd1fgc6q/hzWa/YM4J29RBUisdIUMTfySOTGt2xzLYls13RAvDRkaXpNWm7+PU6VLGL7OLp73V15M2iPJ/IoFdj/iVIihI4LI9D3YbU2w5/N0/e6iSfaBS9NGL+tFvKK/zAlIhyJht8jGLAtpt+ybLP0wC4IKRg7gU3JxJN08MqCIEqnqYvbnqQ3K62yaKxR72uvUmhwzI6TX+wIqx/dZMb0m9w6uI70+zPKBqF9gGAkG7GfG8HyQgoCdJMZjnTbVj4gB4I/OEaTc758wIXhbikOCiaZ3X0uaVPGdvYKXKChjxp4xw4vCiG+VX6+S4PoWhJfUPAkPvcM79V+9G7h+T9lJePrLUXzXQyQJF4IaSa7DK51QWspCst42wvavnAd0jsbqFwwp9ysSPG6yzYcQC+vqQl5kld1j1niMGhC9gfO4VppjTbuR29dApCi6eOO2C+QidZRxFP3ZWsFjRmDDY0jJ+k7YRX5MUhrtKXMjTtrkIERvwMc/l5OpUKRVbW7ddLOmJTajV2Pjk=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: q2WUvhEL6h0/9zR1PhANxS7vLRUnOtETRwFlC5BmTe0+UNtaFmCeLbmEIy7UUj2myMUVWHrgSn+wR6uki9BKLzlNuEtaWNAE5xc3lFC4ApODjGT/Ck2ynIK3KuZGbn56f2Bf/WS8CH3/Gj0Vhpcf7sTTpxbJHV2XCjylqoqUOp3ouytU+ZmoE49nMB8a25dIPEmsxAUpYvrwnAB5jtPn++4Mp4qm6+ToKkCWK/iNPsTklOgT1TxG7GeIAH3uIZl4B8tL16mxmxPDgmSQFNVW6zwWFKr6O3Dlfg3WSqMlt8s0oeJaN0kYVtttQ9++KQwW0mZ1Nhbahb1elCqX8Epu/zWupySwO8yGtnlWVpUdmDzCKqbpHw2jMyrbUH73z0GbbRJYrC0oo+ESo5mdykCiQiCCGYujP9N7Dhj5fFox/c3gz3i//4RT1Dt7W36Uy/3znZUu/Fo+2/zVxlrhYYHlM9npzG4v+Q3uB+5aR9O7KQWbx0PMtKG4isa9CIW27+ARAx5LWO8CuGUak0kCGPlVLW1brTlAP2fVGh7evxhJJBNPCd0Iwn2ucgoQvQCePlH7as/gMdXRYHBSTgSVdz9UfnjWy2ctOJAQEHQ+TWVZCkHFpBTgPSFPQy9P9Ae9pASt0ajvm+iS9MJ8C2DVNvhLQibGKczdVter3uqCjxTH+zE=
      on_success: never
      on_failure: always
      on_pull_requests: false
